# Generated by Django 2.2.7 on 2019-12-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker_app', '0003_card_series_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='set',
            name='total_cards',
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('number', 'set')},
        ),
    ]
