# Generated by Django 2.2.7 on 2019-12-26 14:06

import card_tracker_app.models.action
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker_app', '0004_auto_20191222_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', django_enumfield.db.fields.EnumField(default=0, enum=card_tracker_app.models.action.ActionTypes)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_card', to='card_tracker_app.Card')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_set', to='card_tracker_app.Set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
