# Generated by Django 2.2.7 on 2020-01-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker_app', '0008_remove_action_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='set',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
