# Generated by Django 3.0 on 2020-01-13 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker_app', '0009_auto_20200109_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loan', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_card_owned', to='card_tracker_app.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_card_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
