# Generated by Django 2.2.7 on 2020-01-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker_app', '0011_auto_20200113_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
