# Generated by Django 2.2.7 on 2020-01-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker_app', '0012_card_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
