# Generated by Django 2.2.13 on 2021-08-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_tracker_app', '0013_auto_20200125_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='cards_per_row',
            field=models.IntegerField(default=3),
        ),
    ]
